# Generated by Django 5.2.8 on 2025-11-25 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='base_cost_price',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='custom_profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom profit % (overrides category)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
