# Generated by Django 5.2.8 on 2025-11-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariant_base_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitprice',
            options={},
        ),
        migrations.RemoveField(
            model_name='unitprice',
            name='price',
        ),
        migrations.AddField(
            model_name='unitprice',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Vendor's cost price in this unit (e.g., per kilo, per nusu)", max_digits=10),
        ),
        migrations.AddField(
            model_name='unitprice',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final customer price for this unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
