# Generated by Django 5.2.8 on 2025-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_unitprice_options_remove_unitprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprice',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
