# Generated by Django 5.2.8 on 2025-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_unitprice_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprice',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
