# Generated by Django 5.2.8 on 2025-11-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_unitprice_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_in_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='min_stock_alert',
        ),
    ]
